### PR TITLE
Pin simpletransformers in setup

### PR DESCRIPTION
**Pull request by hgandhi2411**

### CODE REVIEW

**Comment by SamCox822** [comment]
@hgandhi2411 I think we need to add `conda install pytorch cpuonly -c pytorch` to the check-book.yml file?
see https://pypi.org/project/simpletransformers/

**Comment by whitead** [comment]
Is this good @SamCox822 and @hgandhi2411 ?

**Comment by SamCox822** [comment]
It looks like both books are broken still

**Comment by hgandhi2411** [comment]
@whitead can you test this at your end? The book seems to build fine, but some modules fail to import in our local environments.

**Pull request merged**
