### PR TITLE
fix: typos and update ref

### PR DESCRIPTION
**Pull request by kjappelbaum**
hope i'm not too annoying! 

i'm going through this great ressource as I have to prepare some teaching and just note on the fly things i'd update/change. 

for this chapter, i had these additional notes: 

- [ ] I’m not sure with the learning problem definitions. RL seems missing and semi/self-supervised are somehow in between. 
- [ ] Maybe it is good to add a note that if EDA guides the model selection the train/test split needs to happen before EDA to avoid data leakage 
- [ ] For teaching I would probably use the pandas bracket notation instead of the dot notation as it always works 
- [ ] Might be interesting to add a note/or exercise why “batch size is usually as a power of 2 (e.g., 16, 128)|
- [ ]  It might also be interesting to hint at the research about the link between SGD (and the randomness it introduces) and regularization and generalization 
- [ ] “Here we assume $\{y_i\}$ is a class variable and try to separate our features into these classes” might not capture that well the case of density-based clustering, similarly “1. We say that clustering is a type of unsupervised learning and that it predicts the labels. What exactly are the predicted labels in clustering? Write down what the predicted labels might look like for a few data points.”
- [ ]  I feel it cloud be really useful to highlight or hint at some caveats of graph-embedding based clusterings (UMAP/TSNE) 
- [ ]  A ref for the zoo of methods to select k in k-means https://journals.sagepub.com/doi/abs/10.1243/095440605x829

### CODE REVIEW

**Comment by whitead** [comment]
@kjappelbaum Thanks for the suggestions and copy-editing! Your k-means article sounds useful but the link is 404 for me.

**Comment by kjappelbaum** [comment]
ups, sorry: https://journals.sagepub.com/doi/abs/10.1243/095440605x8298

```
@article{pham2005selection,
  title={Selection of K in K-means clustering},
  author={Pham, Duc Truong and Dimov, Stefan S and Nguyen, Chi D},
  journal={Proceedings of the Institution of Mechanical Engineers, Part C: Journal of Mechanical Engineering Science},
  volume={219},
  number={1},
  pages={103--119},
  year={2005},
  publisher={SAGE Publications Sage UK: London, England}
}
```

**Comment by whitead** [comment]
@kjappelbaum The git diff on the notebook insane and I'm having trouble going through the PR. Did you change any content here or is the PR just typos/grammar? Also, what are the changes of bibtex file? Just an autoformatter or did you add/remove references?

**Comment by kjappelbaum** [comment]
>he git diff on the notebook insane and I'm having trouble going through the PR.

sorry, I also linted the code cells with black to make sure they have uniform format across the book. 
I can split this PR in commits for typos, and linting, then you can cherry pick. 

the changes in the bibtex: 
1. One preprint has been published in meantime 
2. Some typos fixed (e.g., springer -> Springer) 
3. Used the vscode Bibtex extension to sort and format

**Comment by whitead** [comment]
Thanks @kjappelbaum, I'll go ahead and merge this in. Thanks for taking the time to explain everything and offering feedback. I think blacking/formatting is fine, but maybe save that for last commit so that it's easy to tell what are content changes vs format changes.

**Pull request merged**
